/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package cs2stats/demoparse/cmd/jni */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 20 "main.go"


#include <jni.h>
#include <stdlib.h>
#include "jni_helpers.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// 解析 demo（阻塞，必须在工作线程调用）。返回 UTF-8 JSON 字节数组；
// 失败时返回 {"version":1,"error":"..."}，调用方用 Kotlin 的 String(bytes, UTF_8) 解码。
extern jbyteArray Java_com_cs2stats_app_data_demo_DemoNative_parseJson(JNIEnv* env, jclass cls, jstring jpath);

// 当前解析进度 0..10000（万分比）。未开始 = 0，结束 = 10000。
extern jint Java_com_cs2stats_app_data_demo_DemoNative_progress(JNIEnv* env, jclass cls);

// 请求取消当前解析：正在读的 reader 会返回错误，ParseToEnd 随即中断。
extern void Java_com_cs2stats_app_data_demo_DemoNative_cancel(JNIEnv* env, jclass cls);

#ifdef __cplusplus
}
#endif
